### ISSUE TITLE
This CTranslate2 package was not compiled with CUDA support 请问这是什么原因

### ISSUE THREAD

**Issue by EarlySummer2018** [Ifan24/GPT_subtitles#6]
lib3/issues/3020
  warnings.warn(
Local video file: https://www.youtube.com/watch?v=UYT2CikcS8I
Traceback (most recent call last):
  File "/Applications/APP/GPT_subtitles.git/main.py", line 347, in <module>
    subtitle_processor.process(args.no_transcribe)
  File "/Applications/APP/GPT_subtitles.git/main.py", line 292, in process
    transcript, srt_file = self.transcribe_audio()
  File "/Applications/APP/GPT_subtitles.git/main.py", line 143, in transcribe_audio
    model = WhisperModel(self.model, device="cuda", compute_type="float16")
  File "/Users/huang/Library/Python/3.9/lib/python/site-packages/faster_whisper/transcribe.py", line 130, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: This CTranslate2 package was not compiled with CUDA support

**Comment by Ifan24** [comment]
我试了下colab的版本似乎没遇上这个错误
https://colab.research.google.com/drive/1XDLFlgew9BzUqNpTv_kq0HNocTNOSekP?usp=sharing

用whisper来识别语音需要用到GPU，如果有了GPU还是有这个错误，可以试一下重装 faster_whisper
pip uninstall faster_whisper
pip install faster_whisper

**Comment by EarlySummer2018** [comment]
> 我试了下colab的版本似乎没遇上这个错误 https://colab.research.google.com/drive/1XDLFlgew9BzUqNpTv_kq0HNocTNOSekP?usp=sharing
> 
> 用whisper来识别语音需要用到GPU，如果有了GPU还是有这个错误，可以试一下重装 faster_whisper pip uninstall faster_whisper pip install faster_whisper

你的python版本是什么

**Comment by Ifan24** [comment]
Python 3.10.12
